version: '3.3'
services:
  tardis-advisor-app:
    image: tardis-advisor
    depends_on:
      - tardis-advisor-mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_HOST=mongo
      - JHIPSTER_SLEEP=10
    ports:
      - 8080
  tardis-advisor-mongodb:
    extends:
        file: mongodb.yml
        service: tardis-advisor-mongodb
